[project]
name = "integration__previnity_negativacao"
version = "0.1.0"
description = "Pipeline previnity_negativacao da secretaria rj-smtr"
dependencies = [
    "httpx>=0.27.0",
    "pandas-gbq>=0.19.0",
]